edit non c or h file (#17)
* edit non c or h file

* fix syntax

* try new ifs

* fix typo

* more complex skipping logic

* more complex skipping

* single outputs check

* better syntax structure

* change syntax further

* indentation fix

* fix syntax

* more syntax changes

* add back run in plan step

* add parens around git command

* add string parenths

* new git command style

* fix fetch depth

* fix typo fetch depth indent

* change exit values

* change exit value

* try new permissions

* remove parenths

* try different exit method

* try simpler output scheme

* change workflows to only run if C files change

* try to make the post job run every time

* why doesn't post skip

* changing more workflows

* update all workflow dispatches

diff --git a/.github/workflows/clang_tidy.yml b/.github/workflows/clang_tidy.yml
--- a/.github/workflows/clang_tidy.yml
+++ b/.github/workflows/clang_tidy.yml
@@ -5,41 +5,48 @@ on:
   pull_request:
 
 jobs:
-  build:
+  check-diff:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
 
-    - name: Check the diff
-      run: |
-        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.(c|h)$'; then
-          echo "RUN=true" >> $GITHUB_ENV
-        else
-          echo "RUN=false" >> $GITHUB_ENV
-        fi
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 2
 
-    - name: Check for early exit.
-      if: ${{ env.RUN }} == 'false'          
-        run: exit 0
+      # The goal is to force this to pass if it does not need to run.
+      - name: Check the diff
+        run: |
+          if git diff --name-only HEAD HEAD~1 | grep -qE '\.(c|h)$'; then
+            echo "run=true" >> $GITHUB_OUTPUT
+          else
+            echo "run=false" >> $GITHUB_OUTPUT
+          fi
 
-    - name: Get CMake
-      uses: lukka/get-cmake@latest 
+  review:
+    runs-on: ubuntu-latest
+    needs: check-diff
+    if: needs.check-diff.outputs.run == 'true'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Generate Compile Commands
-      run: cmake --preset=clang-deb
+      - name: Get CMake
+        uses: lukka/get-cmake@latest 
 
-    - name: Review
-      uses: ZedThree/clang-tidy-review@v0.19.0
-      id: review
-      with:
-        split_workflow: true
+      - name: Generate Compile Commands
+        run: cmake --preset=clang-deb
 
-    - name: Upload artifacts
-      uses: ZedThree/clang-tidy-review/upload@v0.19.0
-      id: upload-review
+      - name: Review
+        uses: ZedThree/clang-tidy-review@v0.19.0
+        id: review
+        with:
+          split_workflow: true
 
-    # If there are any comments, fail the check
-    - if: steps.review.outputs.total_comments > 0
-      run: exit 1
+      - name: Upload artifacts
+        uses: ZedThree/clang-tidy-review/upload@v0.19.0
+        id: upload-review
+
+      # If there are any comments, fail the check
+      - if: steps.review.outputs.total_comments > 0
+        run: exit 1
