indentation fix

diff --git a/.github/workflows/clang_tidy.yml b/.github/workflows/clang_tidy.yml
--- a/.github/workflows/clang_tidy.yml
+++ b/.github/workflows/clang_tidy.yml
@@ -11,40 +11,40 @@ jobs:
       status: ${{ steps.early.conclusion }}
     steps:
 
-      - uses: actions/checkout@v4
+    - uses: actions/checkout@v4
 
-      # The goal is to force this to pass if it does not need to run.
-      - run: |
-          if git diff --name-only HEAD^ HEAD | grep -qE '\.(c|h)$'; then
-            exit 'success'
-          else
-            exit 'skip'
-          fi
+    # The goal is to force this to pass if it does not need to run.
+    - run: |
+        if git diff --name-only HEAD^ HEAD | grep -qE '\.(c|h)$'; then
+          exit 'success'
+        else
+          exit 'skip'
+        fi
 
   build:
     runs-on: ubuntu-latest
     needs: plan
     if: needs.plan.outputs.status == 'success'
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
 
-      - name: Get CMake
-        uses: lukka/get-cmake@latest 
+    - name: Get CMake
+      uses: lukka/get-cmake@latest 
 
-      - name: Generate Compile Commands
-        run: cmake --preset=clang-deb
+    - name: Generate Compile Commands
+      run: cmake --preset=clang-deb
 
-      - name: Review
-        uses: ZedThree/clang-tidy-review@v0.19.0
-        id: review
-        with:
-          split_workflow: true
+    - name: Review
+      uses: ZedThree/clang-tidy-review@v0.19.0
+      id: review
+      with:
+        split_workflow: true
 
-      - name: Upload artifacts
-        uses: ZedThree/clang-tidy-review/upload@v0.19.0
-        id: upload-review
+    - name: Upload artifacts
+      uses: ZedThree/clang-tidy-review/upload@v0.19.0
+      id: upload-review
 
-      # If there are any comments, fail the check
-        if: steps.review.outputs.total_comments > 0
-        run: exit 1
+    # If there are any comments, fail the check
+      if: steps.review.outputs.total_comments > 0
+      run: exit 1
